# Gruvbox Material Dark (WittyJudge) for Alacritty

[colors.primary]
background = "#282828" # bg0
foreground = "#ddc7a1" # fg1

[colors.cursor]
text = "#282828"
cursor = "#ddc7a1"

[colors.vi_mode_cursor]
text = "#282828"
cursor = "#ddc7a1"

[colors.selection]
text = "#282828"
background = "#a89984" # grey2

[colors.normal]
black   = "#32302f" # bg1
red     = "#ea6962" # red
green   = "#a9b665" # green
yellow  = "#d8a657" # yellow
blue    = "#7daea3" # blue
magenta = "#d3869b" # purple
cyan    = "#89b482" # aqua
white   = "#d4be98" # fg0

[colors.bright]
black   = "#7c6f64" # grey0
red     = "#ea6962" # red
green   = "#a9b665" # green
yellow  = "#d8a657" # yellow
blue    = "#7daea3" # blue
magenta = "#d3869b" # purple
cyan    = "#89b482" # aqua
white   = "#ddc7a1" # fg1
